-- PowerGateway 审计库初始化脚本（已归档 · FB-043）
--
-- ⚠️ 本脚本自 2026-07-27 起 **已停用**（FB-043 · CHG-030）：
--    sql_audit_log 表已合并到配置库 powergateway_config（简化客户环境部署，DBA 不建多 schema）。
--    新库客户：直接执行 init.sql 即可（含 sql_audit_log 表）。
--    老库客户升级：执行 migration-audit-to-config.sql 把已有数据从 audit 库迁到 config 库。
--    应用侧 application.yml 的 audit datasource URL 已改为指向 powergateway_config；
--    SqlAuditLogMapper 保留 @DS("audit") 兼容标注（B 方案），datasource bean 保留但物理同库。
--
-- 保留本文件仅供项目决策历史查证，请勿再运行。
