spring:
  datasource:
    dynamic:
      primary: master
      strict: false
      datasource:
        master:
          url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=MySQL
          driver-class-name: org.h2.Driver
          username: sa
          password:
        audit:
          url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=MySQL
          driver-class-name: org.h2.Driver
          username: sa
          password:
  sql:
    init:
      mode: always
      schema-locations: classpath:db/init-h2.sql
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration

powergateway:
  aes:
    key: PowerGateway128K

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
